---
# tasks file for collector 

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - ecs-dashboard

- name: Check if ECS Dashboard Collector already installed
  stat:
    path: "{{ ecs_dashboard_install_dir }}/ecs-metadata-collector-{{ ecs_dashboard_bin_version}}"
  register: collector_version_installed
  changed_when: false
  tags:
    - ecs-dashboard

- name: Check if ECS Dashboard Collector is already downloaded 
  stat:
    path: "{{ ecs_dashboard_download_dir }}/ecs-metadata-collector-{{ ecs_dashboard_bin_version}}.zip"
  register: collector_version_downloaded
  changed_when: false
  tags:
    - ecs-dashboard

- name: Create Collector download directory
  become: yes
  file:
    path: "{{ ecs_dashboard_download_dir }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: 0755
    state: directory
  tags:
    - ecs-dashboard


- name: Download collector
  become: yes
  get_url:
    url: "{{ ecs_dashboard_collector_url }}"
    dest: "{{ ecs_dashboard_download_dir }}//ecs-metadata-collector-{{ ecs_dashboard_bin_version}}.zip"
  when: collector_version_downloaded.stat.exists == False
  tags:
    - ecs-dashboard

- name: Create Collector install directory
  become: yes
  file:
    path: "{{ ecs_dashboard_install_dir }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: 0755
    state: directory
  tags:
    - ecs-dashboard


- name: Unzip Dashboard collector to installation directory
  become: yes
  unarchive:
    src: "{{ ecs_dashboard_download_dir }}/ecs-metadata-collector-{{ ecs_dashboard_bin_version }}.zip"
    dest: "{{ ecs_dashboard_install_dir }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    remote_src: yes
  tags:
    - ecs-dashboard

- name: Create Collector configuration directory
  become: yes
  file:
    path: "{{ ecs_dashboard_config_dir }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}" 
    mode: 0755
    state: directory
  tags:
    - ecs-dashboard

- name: Create run_ecs_collector_for_all_data.sh file
  become: yes
  template:
    src: "run_ecs_collector_for_all_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_collector_for_all_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - ecs-dashboard

- name: Create run_ecs_collector_for_billing_data.sh file
  become: yes
  template:
    src: "run_ecs_collector_for_billing_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_collector_for_billing_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - ecs-dashboard

- name: Create run_ecs_collector_for_object_data.sh file
  become: yes
  template:
    src: "run_ecs_collector_for_object_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_collector_for_object_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - ecs-dashboard

- name: Create run_ecs_collector_for_object_version_data.sh file
  become: yes
  template:
    src: "run_ecs_collector_for_object_version_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_collector_for_object_version_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - ecs-dashboard

- name: Create run_ecs_collector_for_index_init.sh file
  become: yes
  template:
    src: "run_ecs_collector_for_index_init.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_collector_for_index_init.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - ecs-dashboard

- name: Create Collector log directory
  become: yes
  file:
    path: "{{ ecs_dashboard_log_dir }}/ecs-collector-logs"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rwx,o=rwx"
    state: directory
  tags:
    - ecs-dashboard

- name: Create logback.xml file for collector
  become: yes
  template:
    src: "collector_logback.xml.j2"
    dest: "{{ ecs_dashboard_install_dir }}/ecs-metadata-collector-{{ ecs_dashboard_bin_version }}/config/logback.xml"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - ecs-dashboard

