---
# tasks file for cleaner 

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - cleaner

- name: Check if ECS ElasticSearch cleaner is already installed
  stat:
    path: "{{ ecs_dashboard_install_dir }}/ecs-elasticsearch-cleaner-{{ ecs_dashboard_bin_version}}"
  register: cleaner_version_installed
  changed_when: false
  tags:
    - cleaner

- name: Remove already installed ECS Elasticsearch cleaner
  become: yes
  file:
    path: "{{ ecs_dashboard_install_dir }}/ecs-elasticsearch-cleaner-{{ ecs_dashboard_bin_version }}.zip"
    state: absent
  changed_when: cleaner_version_installed.stat.exists == true
  tags:
    - cleaner 

- name: Check if ECS Elasticsearch cleaner is already downloaded 
  stat:
    path: "{{ ecs_dashboard_download_dir }}/ecs-elasticsearch-cleaner-{{ ecs_dashboard_bin_version}}.zip"
  register: cleaner_version_downloaded
  changed_when: false
  tags:
    - cleaner 

- name: Remove already downloaded ECS Elasticsearch cleaner
  become: yes
  file:
    path: "{{ ecs_dashboard_download_dir }}/ecs-elasticsearch-cleaner-{{ ecs_dashboard_bin_version }}.zip"
    state: absent
  changed_when: cleaner_version_downloaded.stat.exists == true
  tags:
    - cleaner

- name: Create Cleaner download directory
  become: yes
  file:
    path: "{{ ecs_dashboard_download_dir }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: 0755
    state: directory
  tags:
    - cleaner

- name: Download cleaner 
  become: yes
  get_url:
    url: "{{ ecs_dashboard_cleaner_url }}"
    dest: "{{ ecs_dashboard_download_dir }}/ecs-elasticsearch-cleaner-{{ ecs_dashboard_bin_version }}.zip"
  tags:
    - cleaner

- name: Create Cleaner install directory
  become: yes
  file:
    path: "{{ ecs_dashboard_install_dir }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: 0755
    state: directory
  tags:
    - cleaner

- name: Unzip Dashboard cleaner into installation directory
  become: yes
  unarchive:
    src: "{{ ecs_dashboard_download_dir }}/ecs-elasticsearch-cleaner-{{ ecs_dashboard_bin_version }}.zip"
    dest: "{{ ecs_dashboard_install_dir }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    remote_src: yes
  tags:
    - cleaner

- name: Create Cleaner configuration directory
  become: yes
  file:
    path: "{{ ecs_dashboard_config_dir }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}" 
    mode: 0755
    state: directory
  tags:
    - cleaner

- name: Create run_ecs_elasticsearch_cleaner_for_all_data.sh file
  become: yes
  template:
    src: "run_ecs_elasticsearch_cleaner_for_all_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_elasticsearch_cleaner_for_all_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - cleaner

- name: Create run_ecs_elasticsearch_cleaner_for_billing_data.sh file
  become: yes
  template:
    src: "run_ecs_elasticsearch_cleaner_for_billing_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_elasticsearch_cleaner_for_billing_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - cleaner

- name: Create run_ecs_elasticsearch_cleaner_for_object_data.sh file
  become: yes
  template:
    src: "run_ecs_elasticsearch_cleaner_for_object_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_elasticsearch_cleaner_for_object_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - cleaner

- name: Create run_ecs_elasticsearch_cleaner_for_object_version_data.sh file
  become: yes
  template:
    src: "run_ecs_elasticsearch_cleaner_for_object_version_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_elasticsearch_cleaner_for_object_version_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - cleaner

- name: Create run_ecs_elasticsearch_cleaner_for_namespace_detail_data.sh file
  become: yes
  template:
    src: "run_ecs_elasticsearch_cleaner_for_namespace_detail_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_elasticsearch_cleaner_for_namespace_detail_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - cleaner

- name: Create run_ecs_elasticsearch_cleaner_for_namespace_quota_data.sh file
  become: yes
  template:
    src: "run_ecs_elasticsearch_cleaner_for_namespace_quota_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_elasticsearch_cleaner_for_namespace_quota_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - cleaner

- name: Create run_ecs_elasticsearch_cleaner_for_vdc_data.sh file
  become: yes
  template:
    src: "run_ecs_elasticsearch_cleaner_for_vdc_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_elasticsearch_cleaner_for_vdc_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - cleaner
    
- name: Create run_ecs_elasticsearch_cleaner_for_bucket_owner_data.sh file
  become: yes
  template:
    src: "run_ecs_elasticsearch_cleaner_for_bucket_owner_data.sh.j2"
    dest: "{{ ecs_dashboard_install_dir }}/run_ecs_elasticsearch_cleaner_for_bucket_owner_data.sh"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - cleaner
    
- name: Create Cleaner log directory
  become: yes
  file:
    path: "{{ ecs_dashboard_log_dir }}/ecs-es-cleaner-logs"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rwx,o=rwx"
    state: directory
  tags:
    - cleaner

- name: Create logback.xml file for cleaner
  become: yes
  template:
    src: "cleaner_logback.xml.j2"
    dest: "{{ ecs_dashboard_install_dir }}/ecs-elasticsearch-cleaner-{{ ecs_dashboard_bin_version }}/config/logback.xml"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
    - cleaner

