---
# tasks file for collector 

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - ecs-dashboard

- name: Check if Chrome driver already installed
  stat:
    path: "{{ ecs_dashboard_install_dir }}/chromedriver-{{ chrome_driver_url_version }}"
  register: chrome_driver_version_installed
  changed_when: false
  tags:
    - ecs-dashboard

- name: Check if Chromer driver is already downloaded 
  stat:
    path: "{{ ecs_dashboard_download_dir }}/chromedriver_linux64.zip"
  register: chrome_driver_version_downloaded
  changed_when: false
  tags:
    - ecs-dashboard

- name: Create Chrome driver download directory
  become: yes
  file:
    path: "{{ ecs_dashboard_download_dir }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: 0755
    state: directory
  tags:
    - ecs-dashboard

- debug:
    msg: "Chrome driver URL {{ chrome_driver_url }}"

- name: Download Chrome Driver 
  become: yes
  get_url:
    url: "{{ chrome_driver_url }}"
    dest: "{{ ecs_dashboard_download_dir }}/chromedriver_linux64.zip"
  #when: chrome_driver_version_downloaded.stat.exists == False
  tags:
    - ecs-dashboard

- name: Create Collector install directory
  become: yes
  file:
    path: "{{ ecs_dashboard_install_dir }}/chromedriver-{{ chrome_driver_bin_version }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    mode: 0755
    state: directory
  tags:
    - ecs-dashboard


- name: Unzip Dashboard collector to installation directory
  become: yes
  unarchive:
    src: "{{ ecs_dashboard_download_dir }}/chromedriver_linux64.zip"
    dest: "{{ ecs_dashboard_install_dir }}/chromedriver-{{ chrome_driver_bin_version }}"
    owner: "{{ ecs_dashboard_user }}"
    group: "{{ ecs_dashboard_group }}"
    remote_src: yes
  tags:
    - ecs-dashboard

