---

- name: search for best installed JRE
  become: yes 
  shell: "update-alternatives --display java | grep best | sed 's/Current `best//g' | sed \"s/' version is //g\" | sed 's/jre.*/jre/g'" 
  register: jre_path
  tags:
    - ecs-dashboard

- debug:
    msg: "Selected JRE: `{{ jre_path.stdout }}`"
  tags:
    - ecs-dashboard

- set_fact: java_home="{{ jre_path.stdout }}"
  tags:
    - ecs-dashboard
